apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: bHVhbm1vcmVub21hY2llbA==
  GITSYNC_USERNAME: bHVhbm1vcmVub21hY2llbA==
  GIT_SYNC_PASSWORD: Z2hwX2gzTTg3NmRWbW0zdUpTSzgxQmQ4ak1CaGo5Z3AzVzFxdHRnYw==
  GITSYNC_PASSWORD: Z2hwX2gzTTg3NmRWbW0zdUpTSzgxQmQ4ak1CaGo5Z3AzVzFxdHRnYw==
