apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/owshq-academy/ws-stack-dados-k8s.git'
    path: infra/src/helm-charts/hive-metastore
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: 'orion-development'
    namespace: metastore
    server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
