apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: argocd-lb-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.18.0.50-172.18.0.110
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: argocd-lb-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - argocd-lb-pool
